# Convolutional Neural Networks (CNNs)

## Prerequisite

Working of NN.

## Theory

Assume that we are playing Tic-tac-toe. how computer would recognize that we draw latter `o` or `x`.

In [ ]:
import numpy as np

In [ ]:
o = np.array([[0,0,1,1,0,0],
     [0,1,0,0,1,0],
     [1,0,0,0,0,1],
     [1,0,0,0,0,1],
     [0,1,0,0,1,0],
     [0,0,1,1,0,0],])


x = np.array([[1,0,0,0,0,1],
     [0,1,0,0,1,0],
     [0,0,1,1,0,0],
     [0,0,1,1,0,0],
     [0,1,0,0,1,0],
     [1,0,0,0,0,1],])

filter = np.array([[0,0,1],
          [0,1,0],
          [1,0,0],])

featureMap = [[0,0,0,0,],
              [0,0,0,0,],
              [0,0,0,0,],
              [0,0,0,0,],]

In [ ]:
o[1:1+3,3:3+3]

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 1]])

In [ ]:
kernal_size = 3
finalsum = 0
for i in range(0,4):
  for j in range(0,4):
    current = o[i:i+kernal_size,j:j+kernal_size]
    finalsum = sum(sum(current*filter))
    featureMap[i][j] = finalsum + (-2)

In [ ]:
featureMap

[[1, -1, -2, -1], [-1, -2, -1, -2], [-2, -1, -2, -1], [-1, -2, -1, 1]]

In [ ]:
def ReLU(x):
  out = np.maximum(0,x)
  return out

In [ ]:
relu_op = ReLU(featureMap)

In [ ]:
relu_op

array([[1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1]])

In [ ]:
max_pool = []
max_pool

[]

In [ ]:
max_pool_size = 2
for i in range(0,4,2):
  for j in range(0,4,2):
    current = relu_op[i:i+max_pool_size,j:j+max_pool_size]
    max_pool.append(current.max())

max_pool

[1, 0, 0, 1]

In [ ]:
max_pool = np.array(max_pool).reshape(2,2)
max_pool

array([[1, 0],
       [0, 1]])

In [ ]:
max_pool = np.array(max_pool).reshape(4)

In [ ]:
max_pool

array([1, 0, 0, 1])

# NN

In [ ]:
w1 = -0.8
w2 = -0.07
w3 = 0.2
w4 = 0.17
b1 = 0.97

w5 = -1.33
w6 = 1.33
b2 = 1.45
b3 = -0.45

In [ ]:
def createFeatureMap(img):
  featureMap = [[0,0,0,0,],
              [0,0,0,0,],
              [0,0,0,0,],
              [0,0,0,0,],]
  kernal_size = 3
  finalsum = 0
  for i in range(0,4):
    for j in range(0,4):
      current = img[i:i+kernal_size,j:j+kernal_size]
      finalsum = sum(sum(current*filter))
      featureMap[i][j] = finalsum + (-2)
  return featureMap

def createMaxPool(op_of_relu):
  max_pool = []
  max_pool_size = 2
  for i in range(0,4,2):
    for j in range(0,4,2):
      current = op_of_relu[i:i+max_pool_size,j:j+max_pool_size]
      max_pool.append(current.max())
  return max_pool

In [ ]:
def nn(ip):
  x_af = (ip[0]*w1) + (ip[1]*w2) + (ip[2]*w3) + (ip[3]*w4) + b1
  y_af = max(0,x_af) # relu
  class_o = (y_af*w5) + b2
  class_x = (y_af*w6) + b3
  return class_o,class_x


In [ ]:
nn(max_pool)

(0.9978, 0.0021999999999999797)

In [ ]:
x_of_af = createFeatureMap(x)

In [ ]:
y_of_af = ReLU(x_of_af)
max_pool = createMaxPool(y_of_af)
nn(max_pool)

(-0.013000000000000345, 1.0130000000000003)